UPD: gcloud-deploy.yml

diff --git a/.github/workflows/gcloud-deploy.yml b/.github/workflows/gcloud-deploy.yml
--- a/.github/workflows/gcloud-deploy.yml
+++ b/.github/workflows/gcloud-deploy.yml
@@ -49,14 +49,14 @@ jobs:
     steps:
       - name: 'Check version'
         run: >
-          if [[ ! ${{ inputs.release }} ]] && [[ ${{ inputs.version }} -ne "latest" ]]; then
+          if [[ ${{ inputs.release }} != "true" && ${{ inputs.version }} != "latest" ]]; then
             echo "::error ::release=false mode supports only latest version [version: ${{ inputs.version }}]";
             exit 1;
           fi;
-#          if [[ ! ${{ inputs.version }} =~ $VERSION_REGEXP ]]; then
-#            echo "::error ::version should match regular expression [version: ${{ inputs.version }}, regexp: $VERSION_REGEXP]";
-#            exit 1;
-#          fi;
+          if [[ ! ${{ inputs.version }} =~ $VERSION_REGEXP ]]; then
+            echo "::error ::version should match regular expression [version: ${{ inputs.version }}, regexp: $VERSION_REGEXP]";
+            exit 1;
+          fi;
 
       - name: 'Check release tag'
         if: ${{ startsWith(inputs.version, 'v') }}
